name: ts_weather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  geolocator: ^13.0.4
  equatable: ^2.0.5
  intl: ^0.19.0
  fpdart: ^1.1.1
  freezed_annotation: ^2.3.2
  connectivity_plus: ^6.1.3
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  retrofit_generator: ^8.0.4
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  freezed: ^2.3.2
  easy_localization_generator: ^0.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/mock_data_test/
    - assets/translations/
  generate: true
